/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-06-06 09:03:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.organizes.custom.organizes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/C:/aymanDocument/projects/bosch/code/boschtags/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boschuihost/WEB-INF/lib/com.bosch.ui.jsp.tags-common-0.0.1-SNAPSHOT.jar!/META-INF/tags/molecules/mainTab.tag", Long.valueOf(1528212648000L));
    _jspx_dependants.put("jar:file:/C:/aymanDocument/projects/bosch/code/boschtags/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boschuihost/WEB-INF/lib/com.bosch.ui.jsp.tags-common-0.0.1-SNAPSHOT.jar!/META-INF/tags/molecules/logo.tag", Long.valueOf(1528213914000L));
    _jspx_dependants.put("jar:file:/C:/aymanDocument/projects/bosch/code/boschtags/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boschuihost/WEB-INF/lib/com.bosch.ui.jsp.tags-common-0.0.1-SNAPSHOT.jar!/META-INF/tags/molecules/search.tag", Long.valueOf(1528212662000L));
    _jspx_dependants.put("jar:file:/C:/aymanDocument/projects/bosch/code/boschtags/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boschuihost/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("jar:file:/C:/aymanDocument/projects/bosch/code/boschtags/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boschuihost/WEB-INF/lib/com.bosch.ui.jsp.tags-common-0.0.1-SNAPSHOT.jar!/META-INF/bosch-molecules.tld", Long.valueOf(1528213364000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528111609314L));
    _jspx_dependants.put("/WEB-INF/lib/com.bosch.ui.jsp.tags-common-0.0.1-SNAPSHOT.jar", Long.valueOf(1528213915571L));
    _jspx_dependants.put("jar:file:/C:/aymanDocument/projects/bosch/code/boschtags/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boschuihost/WEB-INF/lib/com.bosch.ui.jsp.tags-common-0.0.1-SNAPSHOT.jar!/META-INF/tags/molecules/languageSelector.tag", Long.valueOf(1528212660000L));
    _jspx_dependants.put("jar:file:/C:/aymanDocument/projects/bosch/code/boschtags/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boschuihost/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String brandIdentifier;
  private java.lang.String pageLinksText;
  private java.lang.String pageLinksURL;

  public java.lang.String getBrandIdentifier() {
    return this.brandIdentifier;
  }

  public void setBrandIdentifier(java.lang.String brandIdentifier) {
    this.brandIdentifier = brandIdentifier;
    jspContext.setAttribute("brandIdentifier", brandIdentifier);
  }

  public java.lang.String getPageLinksText() {
    return this.pageLinksText;
  }

  public void setPageLinksText(java.lang.String pageLinksText) {
    this.pageLinksText = pageLinksText;
    jspContext.setAttribute("pageLinksText", pageLinksText);
  }

  public java.lang.String getPageLinksURL() {
    return this.pageLinksURL;
  }

  public void setPageLinksURL(java.lang.String pageLinksURL) {
    this.pageLinksURL = pageLinksURL;
    jspContext.setAttribute("pageLinksURL", pageLinksURL);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getBrandIdentifier() != null ) 
      _jspx_page_context.setAttribute("brandIdentifier", getBrandIdentifier());
    if( getPageLinksText() != null ) 
      _jspx_page_context.setAttribute("pageLinksText", getPageLinksText());
    if( getPageLinksURL() != null ) 
      _jspx_page_context.setAttribute("pageLinksURL", getPageLinksURL());

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!-- HEADER -->\r\n");
      out.write("<header class=\"page-header\">\r\n");
      out.write("\t<div class=\"logo-row\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_bosch_005flogo_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t<div class=\"header-meta\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_bosch_005flanguageSelector_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t<h4 class=\"brand-identifier\"> ");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"nav-row\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_bosch_005fmainTab_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_bosch_005fsearch_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"user-action-row\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"header-meta\">\r\n");
      out.write("\t\t\t\t<nav class=\"navigation\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navigation-meta\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"navigation-user-action\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"user-action\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"navigation-meta-link user-action-link\" href=\"/\">Sign\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tIn / Register\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"icon-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"./resources/img/icon/Bosch-IC-my-brand-frame.svg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"user-action\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"navigation-meta-link user-action-link\" href=\"/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"icon-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"./resources/img/icon/Bosch-IC-shoppingcart.svg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
      _jspDestroy();
    }
  }

  private boolean _jspx_meth_bosch_005flogo_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bosch:logo
    org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.molecules.custom.molecules.logo_tag _jspx_th_bosch_005flogo_005f0 = new org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.molecules.custom.molecules.logo_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_bosch_005flogo_005f0);
    try {
      _jspx_th_bosch_005flogo_005f0.setJspContext(_jspx_page_context);
      _jspx_th_bosch_005flogo_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      _jspx_th_bosch_005flogo_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_bosch_005flogo_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_bosch_005flanguageSelector_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bosch:languageSelector
    org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.molecules.custom.molecules.languageSelector_tag _jspx_th_bosch_005flanguageSelector_005f0 = new org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.molecules.custom.molecules.languageSelector_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_bosch_005flanguageSelector_005f0);
    try {
      _jspx_th_bosch_005flanguageSelector_005f0.setJspContext(_jspx_page_context);
      _jspx_th_bosch_005flanguageSelector_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      _jspx_th_bosch_005flanguageSelector_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_bosch_005flanguageSelector_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      // /META-INF/tags/organizes/header.tag(21,34) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setKey("iot.identifier");
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bosch_005fmainTab_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bosch:mainTab
    org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.molecules.custom.molecules.mainTab_tag _jspx_th_bosch_005fmainTab_005f0 = new org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.molecules.custom.molecules.mainTab_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_bosch_005fmainTab_005f0);
    try {
      _jspx_th_bosch_005fmainTab_005f0.setJspContext(_jspx_page_context);
      _jspx_th_bosch_005fmainTab_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      // /META-INF/tags/organizes/header.tag(27,2) name = pageLinksText type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_bosch_005fmainTab_005f0.setPageLinksText((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageLinksText}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /META-INF/tags/organizes/header.tag(27,2) name = pageLinksURL type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_bosch_005fmainTab_005f0.setPageLinksURL((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageLinksURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      _jspx_th_bosch_005fmainTab_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_bosch_005fmainTab_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_bosch_005fsearch_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bosch:search
    org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.molecules.custom.molecules.search_tag _jspx_th_bosch_005fsearch_005f0 = new org.apache.jsp.tag.meta.http_003a.bosch_com.taglib.molecules.custom.molecules.search_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_bosch_005fsearch_005f0);
    try {
      _jspx_th_bosch_005fsearch_005f0.setJspContext(_jspx_page_context);
      _jspx_th_bosch_005fsearch_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      _jspx_th_bosch_005fsearch_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_bosch_005fsearch_005f0);
    }
    return false;
  }
}
