/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-06-04 13:49:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.meta.http_003a.bosch_com.ioteco.taglib.custom;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class marketingText_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("<!-- Buyers Sellers Block -->\r\n");
      out.write("\t<section class=\"buyers-sellers-section\">\r\n");
      out.write("\t\t<p class=\"buyers-sellers-title\">\r\n");
      out.write("\t\t\t<span class=\"block-header\">Where buyers and sellers of</span>\r\n");
      out.write("\t\t\t<Span class=\"block-header\">cross-industry IoT products, services</span>\r\n");
      out.write("\t\t\t<Span class=\"block-header\">and solutions meet</span>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p class=\"block-content\">\r\n");
      out.write("\t\t\t<span>The Bosch IoT Marketplace offers secure collaboration for buying and selling IoT products, services and solutions that\r\n");
      out.write("\t\t\t\tcan be developed with the help of the Developer Portal. By bringing together our partners, customers, developers and\r\n");
      out.write("\t\t\t\tdifferent Bosch Domains, this platform is the perfect breeding ground for your business to generate new business models\r\n");
      out.write("\t\t\t\tand additional revenue streams.</span>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p class=\"block-content block-content-width\">\r\n");
      out.write("\t\t\t<span class=\"block-content-parent\">\r\n");
      out.write("\t\t\t\t<span>1.</span>\r\n");
      out.write("\t\t\t\t<span class=\"block-content-child\">For Customers: The Bosch IoT Marketplace provides access to some of the most innovative, state-of-the-art, end-to-end,\r\n");
      out.write("\t\t\t\t\tIoT solutions and services currently available, all developed within a trustworthy environment. To read more about this\r\n");
      out.write("\t\t\t\t\tgo to: www.xxx.xxx\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<span class=\"block-content-parent\">\r\n");
      out.write("\t\t\t\t<span>2.</span>\r\n");
      out.write("\t\t\t\t<span class=\"block-content-child\">For Partners & Resellers: The Bosch IoT Marketplace allows both partners and resellers to manage and market IoT solutions,\r\n");
      out.write("\t\t\t\t\tsoftware, tools and services running in the Bosch IoT Cloud and other (cloud) environments. To find out more contact\r\n");
      out.write("\t\t\t\t\tour consultancy team at: www.xxx.xx\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<span class=\"block-content-parent\">\r\n");
      out.write("\t\t\t\t<span>3.</span>\r\n");
      out.write("\t\t\t\t<span class=\"block-content-child\"> Developers: The Bosch Developer Portal allows developers to build and deploy their own IoT buildings blocks and connect\r\n");
      out.write("\t\t\t\t\twith the world's foremost IoT Marketplace. The Developer Portal also provides a bank of re-usable software components,\r\n");
      out.write("\t\t\t\t\tblueprints, sensors and documentation It also allows developers to sell their own solutions in the Bosch IoT Marketplace\r\n");
      out.write("\t\t\t\t\tand benefit from a seamless, yet simple selling experience, to reach a broad IoT focused audience. To find out more\r\n");
      out.write("\t\t\t\t\tsee the Bosch Developer Portal at: www.xxx.xx\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</section>\r\n");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
