/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-06-04 13:49:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.meta.http_003a.bosch_com.ioteco.taglib.custom;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MarketingCarousel_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("<section class=\"industrie-section\">\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<span class=\"industrie-header main\">Our products for Industrie 4.0</span>\r\n");
      out.write("\t\t\t<Span class=\"industrie-header\">Enabling a connected industry</span>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<div class=\"slide-container\">\r\n");
      out.write("\t\t\t<div class=\"industrie-slides slide-container slider-animate-right\">\r\n");
      out.write("\t\t\t\t<div class=\"slider-container-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container image\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"image-height\" src=\"resources/img/u70.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container content banner\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"text-content-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore\"\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-content-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<svg height=\"20\" width=\"200\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<g fill=\"none\" stroke=\"#ffffff\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<path stroke-width=\"1\" d=\"M9 20 8015 0\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</g>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-right\">AUTHOR NAME, DEPARTMENT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-right\">COMPANY NAME</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"slider-container-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container content headers even-headers\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"main\">Solution</span>\r\n");
      out.write("\t\t\t\t\t\t<Span class=\"sub\">Lorem</span>\r\n");
      out.write("\t\t\t\t\t\t<Span>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container image\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"image-height\" src=\"resources/img/u70.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"industrie-slides slide-container slider-animate-right\">\r\n");
      out.write("\t\t\t\t<div class=\"slider-container-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container content banner even-left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"text-content-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore\"\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-content-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<svg height=\"20\" width=\"200\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<g fill=\"none\" stroke=\"#ffffff\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<path stroke-width=\"1\" d=\"M9 20 8015 0\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</g>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-right\">AUTHOR NAME, DEPARTMENT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-right\">COMPANY NAME</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container image\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"image-height\" src=\"resources/img/u70.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"slider-container-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container image\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"image-height\" src=\"resources/img/u70.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container content headers even-right\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"main\">Solution</span>\r\n");
      out.write("\t\t\t\t\t\t<Span class=\"sub\">Lorem</span>\r\n");
      out.write("\t\t\t\t\t\t<Span>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"industrie-slides slide-container slider-animate-right\">\r\n");
      out.write("\t\t\t\t<div class=\"slider-container-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container image\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"image-height\" src=\"resources/img/u70.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container content banner\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"text-content-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore\"\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-content-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<svg height=\"20\" width=\"200\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<g fill=\"none\" stroke=\"#ffffff\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<path stroke-width=\"1\" d=\"M9 20 8015 0\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</g>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-right\">AUTHOR NAME, DEPARTMENT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"slider-right\">COMPANY NAME</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"slider-container-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container content headers even-headers\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"main\">Solution</span>\r\n");
      out.write("\t\t\t\t\t\t<Span class=\"sub\">Lorem</span>\r\n");
      out.write("\t\t\t\t\t\t<Span>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-container image\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"image-height\" src=\"resources/img/u70.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"slide-buttons\" align=\"center\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span class=\"slider-badge slider-transparent slider-hover-white\" onclick=\"currentDiv(1)\"></span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span class=\"slider-badge slider-transparent slider-hover-white\" onclick=\"currentDiv(2)\"></span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span class=\"slider-badge slider-transparent slider-hover-white\" onclick=\"currentDiv(3)\"></span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
